### ISSUE TITLE
add fake functions to templates

### ISSUE THREAD

**Issue by jryannel** [apigear-io/cli#108]
E.g. it shall be possible to create fake data for properties, functions, etc.

This shall allow the code generator and the simulation to use fake data

```
properties:
  - name: value
    type: int
    fake: number:1,10
```

or 

```
@fake: {number:1,10}
value: int
```

in the simulation

```
properties:
  - name: value
    value: 0
    fake: number:1,10
```

See also https://github.com/brianvoe/gofakeit
