### ISSUE TITLE
interface references

### ISSUE THREAD

**Issue by jryannel** [apigear-io/cli#129]
Allow interfaces to be used in the API surface, they should already be usable but it is not sure if all templates support them.

Here is an example:

```
interface Radio { ... }
interface Registry {
  get(name: string): Radio
}
```

To make this work we need to ensure that all filters in all technologies do return interfaces. 

We need also decide if interfaces in structs are allowed?

**Comment by jryannel** [comment]
You can add now interfaces as part of your references:

## IDL

```
module demo 1.0


interface Common {
    value3: int
}

interface Counter {
    getCommon(): Common
}
```

## YAML

```
name: demo
version: "1.0"

interfaces:
  - name: Common
  - name: Counter
    operations:
      - name: getCommon
        return:
          type: Common
```

## Code

Will result into code like 

```go

package demo

// Data Structures
type Common interface {
    // Methods

}
type Counter interface {
    // Methods
    GetCommon() Common
}
```

## Filters

In the filters only the interface case needs to be handled:

```
func ToReturnString(prefix string, schema *model.Schema) (string, error) {
  ...
	case model.TypeInterface:
		text = fmt.Sprintf("%s%s", prefix, schema.Type)
  ...
}
```
