### ISSUE TITLE
extending interfaces

### ISSUE THREAD

**Issue by jryannel** [apigear-io/cli#131]
The idea is to allow interfaces to extend other interfaces.

E.g.

```
interface A {}
interface B extends A {}
```

in YAML this would be

```
interfaces:
  - name: B
    extends: A
```

For C++ we would extend one interface with another:

```
class B extends A {};
```

**Comment by jryannel** [comment]
Now you can extend interface using the extends keyword:

- We don't allow multi extends, only single extends

## IDL

```
interface Common {
}

interface Counter extends Common {
}
```

or using an external type:

```
import demo

interface Counter extends demo.Common {
}
```

## YAML

```
name: demo.bbb
version: "1.0"

imports: 
  - name: demo.aaa

interfaces:
  - name: Common
  - name: Counter
    extends:
      name: Common
      import: demo.aaa
```

## Template

In the go template we can then access the extends information:

- TODO: Make the extends simpler in go (how does it look in C++/Rust?)
```
{{- range .Module.Interfaces }}
{{- $class := .Name }}
type {{$class}} interface {
{{- if .HasExtends }}
    {{- if .Extends.Import }}
    {{camel (splitLast .Extends.Import ".")}}.{{Camel .Extends.Name }}
    {{- else }}
    {{Camel .Extends.Name }}
    {{- end }}
{{- end }}
}
{{- end }}
```
