### ISSUE TITLE
deprecate operation in favour of method

### ISSUE THREAD

**Issue by jryannel** [apigear-io/cli#139]
Always when I try to write the word operation I start with the word method. I feel this is for a long time something we should have changed. 

When looking into OOP methods are the members of an object. It should feel more natural for users. 

We can still support operations, but mark them a deprecated.

```
interfaces:
  - name: A
    operations:
      - name: add
```

would become:

```
interfaces:
  - name: A
    methods:
      - name: add
```
